#ifndef CLIENTSTATES_H
#define CLIENTSTATES_H

enum CLIENT_STATE
{
    NOTSTARTED = 0, RUNNING = 1, STOPPED = 2, FINISHED = 3
};

enum CLIENT_STATUS
{
    ERROR = -1, CONNECTED = 0, DISCONNECTED = 1
};

#endif // CLIENTSTATES_H
